const photos = {
  redRing: "https://lh3.googleusercontent.com/aida/AEtjO1W5Pzk1LAKMOV88xP5WVDtRm3lQYGOBQTt95picJ_G8zOlx_4bYks9lHN5pIdjJf9CKtg1ZsxsFKMvzAu33L9JdzeeWsjTrTNA6cuKlXI_ZcL-ozjtSwl2jfOiM2xIW_vKf0JzfZIy-_7GvOWGLt4ngATzlIycl6KjKMRFwP49MECMZcJLzsLsP0j1lhGhdXksCuA5Dx2X2q-lZ7URlISw5QSwP1h0KYr1uHGLdHUE7lgiZSul19Rm6evKbklrCiyzMIY7bk-vwPGQ",
  ringHands: "https://lh3.googleusercontent.com/aida/AEtjO1WHZk08PHEEZeDHOcrToISqMrcLWMpGqH8Mo0dxIAhY0D_bwcgAkhMhlXsB_3hRogtUnngSSxeKlSTnjON2__bjywRlQcZrEg1NdKgD6J6h4oYSHKqiYsu4Ft1naRsVDfHJ0C0xBvAjokAIK19aOrfl4MiDBtrYrSdceMcowPdUbMiGWNCVCNZ5pTJRmr-hDMPJqVvocVKeQh-epKBQch5PuRT0pStpcsFVAD2_MpMxv1AEMUoCkitKZC1QcKRFualkxdRGIWpTncY",
  redPendant: "https://lh3.googleusercontent.com/aida/AEtjO1X0-5Hxp9PKaRSvGU8MMuY-llBCHc8vgSAOLOUk2hNx9Im8X3tzHzD7HAfOlpRinhpLQb7V8kaBNnhIEQkh8zUNgXpJKCZHkqT9ut7pv1zL3wx9NPQOm71zNKxrkPEDIzPEJI1udOJyDxrIqrqEQXIaMamuTDLAqWrjdtKXX7BZdyls-HG9XsF7Uqo1mqQnLhivPddtVT4wYjn9h8spIARABDTebH-87eW6cZdn6dRJ-WoCXc9aT6IPKr6bK2CuWZ48jDURKxcNFC8",
  squareRing: "https://lh3.googleusercontent.com/aida/AEtjO1Xh7T9_ze1DVI3tjmOx9DqLADLiCb-sWqfm8D30uDDLJq83fS7Lz_v3-55MMpcC_cSZr6i58Yx3HhSANmAnTaJdBnfUHCkiSTjdkfBbdCPkCyVWxNzQH_QqzxwfQPldvOTgcsiaP3ss8DqTL5RcWQXfGK7JUcyqC86cd2r5mRvfrAauukgb_FNBIGVngFGY8CB3okBY4ymFhl8Vf_likm2AF8Ldy9Un1Kph2NOEzy8YMVN3IInRePVRfuc8uHcuaeXc8WTUzngPng",
  blueRing: "https://lh3.googleusercontent.com/aida/AEtjO1W5mmMQJKS3P2DJCJIiwKU3jFUkqtv1X9ApVcPJONS-G32mX1H5UN1OyOaT6rAF1pp1z8xriKDemX26xTSzUGL0_qS84ZSO5kjkTgN4Mxt05-cwsloCpVxqOyHgqGJBhH-B-xAUObITS7zEiNNd0PKLDxi0-PtrhTb8QwV4VWdXomp0zy_R4PU_CJvKh-y60SfFL34bSvulold12bVFRcY3wKfMHVC8PU2MlLNSbvlvvubM0V-9AwK-V2HK5qxHVEn0u6e6fduYWA",
  stars: "https://lh3.googleusercontent.com/aida/AEtjO1XogAPKm96P3bp2iOg_9Bxx9fZ-sf7oxfEqJNlTOVVl04ClRG4UI5LR6x7ZwoWSqg9a6hPUenP5k8nQ-AvxR4IeneQX8wSP1MtfDhxzNZKsRt8OX5bm8PB4ewvZDJlaWoqkZYtcunHz-imEFdzhavFlAXluoMco5srOMXtp7CHgVkvR4RzYWQoviBZPa_10KsjpyAHidfEQdYLg4ObtzRAiSbs7UM0FbF1HWCgLoy2ZwYZ0hI2f7QaMbYw2e05ab9oNaP28TPQh7A",
  handRed: "https://lh3.googleusercontent.com/aida/AEtjO1VnVUk_rN54pNifoIM47sVF9hX-zfhW9VcsiTMkxjNezpT0VkwEhbx50DSF7bqhKX0sxFTlRH8pp9AW177PAe-AV5ZVnQiKhn7avniek6KlzHU2kqSFO-RiZLCy9AZVt11nJsOdonfaLcfR6AbJRQn0D-8PMsXkUnFUPJaHubC-R8txsP-iqFqbZ0qZg8yVvGb5HuK0dVpAHKTamhlSDIgekQblFeYs2LJaBHq5c_ow7gNVddsvZyeylrnKt9W1xY5LVOpKwmJqPA",
  amberRing: "https://lh3.googleusercontent.com/aida/AEtjO1UsHTzJ2aojkfX7csXl1IegoLcLXfrqsriCgOOwcn_B4rm0CGYRDbFnPkwOg0jfln7iGDZySIO-F7NCC2RMQSaWe_xb5oe5m8DOsxtsUyI_tRdtnfi2wP7gHBklgwfuF9eNsoQaAjX3EigU49yZ1VxI2yYyKNZvjlcRHPkV_ZTD9UKoEOWt8InzuRj9PM7mtV2Dby66niJhysZAVhM5OgSiQeg0nWpzlBH4lk0kTwBTq9kM-GL_cNjz8WQhPkyLq51TFSA-AxszLA",
  portrait: "https://lh3.googleusercontent.com/aida/AEtjO1V4ysScByVuqUmaCHlSEFnvrJeNFU9UOM7o5JGPNYSn5kUkO9pY_J4I6LEGqEiWD7099yCjT-h8Yy1wYyzMuqpLb3iYLOIYanho3SVWgmKuMVKV1vSP8_A7Yy52rYYlm2zeQ0C2_sYweABvy8VdeUkFC-wue0PUmzUi38kBlJSuJmkBfW1f6FrR1Irw2c_mFI_-9ea0AFkokfeMSXcbdpKS46ssifi6FbxK4N8_1uPvkVeCtY_HOyEUhEVQh8TpxN4bfKlFrPcPnKg",
  silverObject: "https://lh3.googleusercontent.com/aida/AEtjO1VifNuK2YzqMMcafvOWL-ZyAQqAEUM6RhvLuOityM4zrYoWeiAp6YRGy0s1KCjEj-Ymf_62JK6guJ3bl_3cmYeUpeDbNL5QFxQrsJ0ayKJf5wauFsC_tTWpoCwYWJvVErWnpSMlCO071e9Wg47UrJaBvj4OBqmpBupnQwdmXKZW2MhMV39z1VG99V-JqXibdvunvOqM1cQW9veCFRqS3sXCmQeDWHgvygY8hFUd2OzCN6UxtkGYRj-mR2m1QE4KvRrqMPg_mthCSjU",
  onHand: "https://lh3.googleusercontent.com/aida/AEtjO1VGaud-ApD3ykN2J_hSbls0CBKhIWnuezeE8QhJavH1MBZfcmVcilqlbuufxnh3mA0eWkLi4YuECOz0lWIwQeuD1cPz6h49XEypTStHPb0GKpFBWx9HrytMxCBkIT0WIyvw-17a5jvhgcicu5pzbebgS9LCAftQ_s4ERgSeeIV0ode0ge0kRKhSSeGFJ2LfTHNaU5WSE1pDrqWFSX8pVBpPepw3GQY0ei0P6y5REWAq5sJTRLTMS3PqAc3g-q_-5NvhRTuSVLe89tA",
  gemRing: "https://lh3.googleusercontent.com/aida/AEtjO1WxVr1EweQXmagMLtv9vQEQQKAviQjhNl2jlKXGpzEiFKES1CYcviSPkTRLyG8Rc1JcREmERW6Y93n5ENziJrQ5bJBk5d4NcNNJQRuE1_RaFDGCQHdWMsHIEBnOy6lp09PegSeacyehcl_Btc0z-jSrxAU55EMA-rvAo7zQbbHPRA4d_kSAwA2lQz7hZ85lxXuwpg6M0lhrnC1yc8CQv1ywyATGihdhmo26C5vxD4FKV-cJq4XPTifVk5kCbfVg8reZ5X-JIMc8GQM",
  pendantClose: "https://lh3.googleusercontent.com/aida/AEtjO1UhjbfaY2yfvAA1bnwBF1PBK7a26pPl5kmrahNWlC6hk3zcXqpXxmgEjKnava8THlo75X92f0Rqz-g00kicG8SFFMZCAEjHp4geqxsUSYV8ZUywS9zLhaKgT7BWeHx0T6Ymlcv2hi3c8Yoajim295b9LTTf_KlsBYH8v2HHTmRe5qde_UlkvtC1qud7cO9JmKlIT1k8FmHmupq-qsaq2ApBWdf9KUzeh6lhL-9iallU_AxwZ7Wca-ESPZTGLg-x754sn9SCwBQ8vTI",
  ringsStill: "https://lh3.googleusercontent.com/aida/AEtjO1UdeaGcQBm3pvk6T5tejvsEXVeLPZBNB12xnuqh9d1HEeD_mfF-_yvgNq63l30R7A5BYpcnpaO02uaqNEYwuG7xpe_D_texdgh0xSd0uKNeKdiNq3R-R55MNWnA4oY_S_cvvefEnAu0ycqTRUB2WT90LhjaHroEdVcXrMIdahdcaxLx_DfI1OQQhrHVSssJdgekVmK0mn2mmybr49tpMwASrGKrYrZEqdwwn3Z5b0V_AfqpDn6YSqab8Po4QTrdzUm0G9SEsWAQFRM",
  layered: "https://lh3.googleusercontent.com/aida/AEtjO1WyJAK6OunQQPFIEAvR0M5SNV7NjpNXwwjRzTiUnsUZUzMdtOZFXIp6oZg9RFOzj9ERROA7hbEB_5X5qJ8iR1vqfQ1iFPdx2C5pIV8ySDLPau8LGDm8YhagPapHvUXmGDZtofe74uuTc7Va-MCfDa7EF-uUhnt9NVLY_oJH2BbCqCrMF7aSE-MN_SC-vjYe-SJBFaGEanCTsi0RlhzAZSgAl_tmqpkyv2rQjL9gncJGPVpszanugkEWROUOYSeuJurVIRuH_SmejL8",
  darkRing: "https://lh3.googleusercontent.com/aida/AEtjO1VjIZhdiKIlOsytSxPQCiqPBAlB5nuU-w7Oxt8B0E1BJmXcrO6YnbUtvdjR2Bwct9m1P2HzeZ5cOWDpb_ieM3PZTKIDOeBoDXH89-QNjpMh4Lqj5vsNXh1LG3gsWplHb290g9ZgBZxgw36_ziRZaKUs4nmmvevvVelewyK0uqbA7uXehZedD5MERgpnModnuUUOZEVccitBjfsFRtbxABt3AI9rrpnzOSkrMLPAiUx3b6u5hekTMTa5DSgYHA--h0CAE4tvQJWm0bQ",
};

const products = [
  { id: "vesna-pendant", name: "ПОДВЕСКА [VESNA]", price: 14000, type: "Подвески", image: photos.pendantClose, story: "Про соединение четырёх сторон: тела, разума, чувств и души. Это не религиозный символ, это личная точка равновесия и баланса." },
  { id: "hidden-glow", name: "КОЛЬЦО {СКРЫТОЕ СИЯНИЕ}", price: 10000, type: "Кольца", image: photos.gemRing },
  { id: "crimson-faith", name: "ПОДВЕСКА {БАГРОВАЯ ВЕРА}", price: 13500, type: "Подвески", image: photos.silverObject },
  { id: "metamorphoses", name: "КОЛЬЦО {МЕТАМОРФОЗЫ}", price: 9500, type: "Кольца", image: photos.ringsStill },
  { id: "yeah", name: "КОЛЬЦО-ПЕЧАТКА {YEAH}", price: 12000, type: "Кольца", image: photos.darkRing },
  { id: "dangerous-beauty", name: "КОЛЬЦО-КАСТЕТ {ОПАСНАЯ КРАСОТА}", price: 10500, type: "Кольца", image: photos.layered },
  { id: "vesna-ring", name: "КОЛЬЦО [VESNA]", price: 11000, type: "Кольца", image: photos.onHand },
  { id: "sorry-cool", name: "ПОДВЕСКА {SORRY I’AM SO COOL}", price: 13000, type: "Подвески", image: photos.portrait },
  { id: "not-like-others", name: "КОЛЬЦО {NOT LIKE OTHERS}", price: 10500, type: "Кольца", image: photos.redRing },
  { id: "wear-here", name: "КАФФ {ПОКА ЗДЕСЬ ПОНОШУ}", price: 7000, type: "Серьги", image: photos.stars },
  { id: "duality", name: "КОЛЬЦО {DUALITY}", price: 9500, type: "Кольца", image: photos.amberRing },
  { id: "branches", name: "КОЛЬЦО {ВЕТВИ}", price: 10000, type: "Кольца", image: photos.blueRing }
];

const page = new URLSearchParams(location.search).get("page") || "home";
const activeProduct = products.find((item) => item.id === new URLSearchParams(location.search).get("id")) || products[0];
const rubles = (amount) => new Intl.NumberFormat("ru-RU").format(amount) + " ₽";
const link = (to, label, extra = "") => `<a ${extra} href="?page=${to}">${label}</a>`;
const image = (src, alt, cls = "") => `<img class="${cls}" src="${src}" alt="${alt}" loading="lazy">`;
const navItems = [["catalog", "Украшения"], ["workshop", "Мастерская"], ["custom", "Индивидуальный заказ"], ["care", "Уход"]];
const header = `<div class="announcement">Украшения, в которых есть место вашему смыслу</div><header class="site-header"><a class="wordmark" href="?page=home" aria-label="ALTAR’, главная">ALTAR<span>’</span></a><nav class="main-nav" aria-label="Основная навигация">${navItems.map(([to, title]) => link(to, title)).join("")}</nav><div class="header-actions">${link("contacts", "Контакты", "class=header-contact")}<a class="cart-link" href="?page=cart" aria-label="Корзина">Корзина <span id="cart-count">0</span></a></div><button class="menu-button" aria-label="Открыть меню" aria-expanded="false">Меню</button></header>`;
const footer = `<footer class="site-footer"><a class="wordmark" href="?page=home">ALTAR<span>’</span></a><p>Сделано с вниманием<br>в Москве</p><nav aria-label="Навигация в подвале">${navItems.map(([to, title]) => link(to, title)).join("")}${link("contacts", "Контакты")}</nav><span class="copyright">© ALTAR’</span></footer>`;
const productCard = (item, index = 0) => `<article class="catalog-card ${index % 5 === 2 ? "card-offset" : ""}"><a class="card-photo" href="?page=product&id=${item.id}">${image(item.image, `Украшение ALTAR’ — ${item.name}`)}<span class="card-arrow" aria-hidden="true">↗</span></a><div class="card-info"><a href="?page=product&id=${item.id}" class="card-name">${item.name}</a><span>${rubles(item.price)}</span></div><p class="card-kind">${item.type}</p></article>`;
const productGrid = (items) => `<div class="catalog-grid">${items.map(productCard).join("")}</div>`;

const pages = {
  home: () => `<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">Авторские украшения · Москва</p><h1>Найти своё.<br><em>Носить своё.</em></h1><p class="hero-intro">Украшения ALTAR’ — личные символы. Форма встречается с вашим собственным смыслом.</p>${link("catalog", 'Выбрать украшение <span aria-hidden="true">↗</span>', "class=text-link")}<div class="hero-index"><span>01</span><span class="index-rule"></span><span>Коллекция ALTAR’</span></div></div><figure class="hero-image">${image(photos.redRing, "Серебряное украшение ALTAR’ на фактурном фоне")}<figcaption>Объект для личной истории <span>ALTAR’ · Москва</span></figcaption></figure></section><section class="intro section-wrap"><p class="eyebrow">Не украшение ради украшения</p><h2>Красота, в которой<br>можно <em>узнать себя.</em></h2><p class="intro-note">У вещи может быть своё значение. Вы решаете, каким оно станет.</p></section><section class="selection section-wrap"><div class="section-heading"><div><p class="eyebrow">Из мира ALTAR’</p><h2>Найти свой символ</h2></div>${link("catalog", "Вся коллекция <span aria-hidden=true>↗</span>", "class=text-link")}</div><div class="editorial-grid"><a class="editorial-tile" href="?page=catalog">${image(photos.ringHands, "Украшения ALTAR’ на руке")}<span>Кольца <b>↗</b></span></a><a class="editorial-tile editorial-tile--low" href="?page=catalog">${image(photos.redPendant, "Подвеска ALTAR’ на красном фоне")}<span>Подвески <b>↗</b></span></a><a class="editorial-tile" href="?page=catalog">${image(photos.stars, "Украшение ALTAR’ среди свечей")}<span>Серьги и каффы <b>↗</b></span></a></div></section><section class="craft"><div class="craft-image">${image(photos.amberRing, "Деталь фактуры авторского украшения ALTAR’")}</div><div class="craft-copy"><p class="eyebrow">Создано вручную</p><h2>Материал.<br>Форма.<br><em>Прикосновение.</em></h2><p>У каждой вещи свой характер. Здесь фактура и форма говорят сами за себя.</p>${link("workshop", "О мастерской <span aria-hidden=true>↗</span>", "class=text-link")}</div></section><section class="custom section-wrap"><p class="eyebrow">Индивидуальный заказ</p><h2>Образ, который<br><em>пока существует только у вас.</em></h2>${link("custom", "Рассказать идею <span aria-hidden=true>↗</span>", "class=button-link")}</section></main>`,
  catalog: () => `<main id="main"><section class="page-intro"><p class="eyebrow">Объекты ALTAR’</p><h1>Украшения<br><em>своего смысла.</em></h1><p>Выберите форму, которая отзывается именно вам.</p></section><section class="catalog-section section-wrap"><div class="filter-row" role="group" aria-label="Фильтр по типу украшения"><button class="filter-chip is-active" data-filter="Все">Все украшения</button>${["Кольца", "Подвески", "Серьги"].map((name) => `<button class="filter-chip" data-filter="${name}">${name}</button>`).join("")}</div><div id="catalog-grid">${productGrid(products)}</div></section></main>`,
  product: () => `<main id="main"><div class="breadcrumbs">${link("home", "Главная")}<span>/</span>${link("catalog", "Украшения")}<span>/</span><span>${activeProduct.name}</span></div><section class="product-detail"><div class="detail-photo">${image(activeProduct.image, `Украшение ALTAR’ — ${activeProduct.name}`)}</div><div class="detail-copy"><p class="eyebrow">${activeProduct.type} · ALTAR’</p><h1>${activeProduct.name}</h1><p class="detail-price">${rubles(activeProduct.price)}</p><p class="detail-story">${activeProduct.story || "У вещи есть собственный характер. Пусть её значение сложится из вашей истории и того, как вы её носите."}</p><div class="fact-note">Подробности об изделии и доступности можно уточнить у мастерской.</div><button class="button-link add-to-cart" data-id="${activeProduct.id}">Добавить в корзину <span aria-hidden="true">＋</span></button><p class="detail-caption">Изображение из материалов ALTAR’</p></div></section><section class="related section-wrap"><div class="section-heading"><div><p class="eyebrow">Продолжить знакомство</p><h2>Другие формы</h2></div>${link("catalog", "Вся коллекция ↗", "class=text-link")}</div>${productGrid(products.filter((item) => item.id !== activeProduct.id).slice(0, 3))}</section></main>`,
  custom: () => `<main id="main"><section class="split-page"><div class="split-image">${image(photos.handRed, "Украшение ALTAR’ в выразительной композиции")}</div><div class="split-copy"><p class="eyebrow">Индивидуальный заказ</p><h1>Ваша идея.<br><em>Наша мастерская.</em></h1><p>Если нужная форма пока существует только в воображении, расскажите о ней. Можно обсудить украшение или другой объект из серебра.</p><div class="steps"><div><span>01</span><p>Опишите замысел и приложите референсы.</p></div><div><span>02</span><p>Мастерская обсудит форму и возможность работы.</p></div><div><span>03</span><p>Детали, сроки и стоимость согласуются отдельно.</p></div></div>${link("contacts", "Связаться с мастерской <span aria-hidden=true>↗</span>", "class=button-link")}</div></section></main>`,
  workshop: () => `<main id="main"><section class="workshop-hero"><div><p class="eyebrow">За каждым объектом — руки</p><h1>Мастерская<br><em>ALTAR’.</em></h1><p>Место, где материалу дают обрести собственную форму.</p></div><figure>${image(photos.squareRing, "Фрагмент авторского украшения ALTAR’")}<figcaption>Форма в деталях</figcaption></figure></section><section class="workshop-story section-wrap"><div class="workshop-aside"><p class="eyebrow">Подход</p><span>01 — 03</span></div><div><h2>Не тираж.<br><em>Характер.</em></h2><p>ALTAR’ соединяет выразительную форму и личный смысл. Мы сохраняем внимание к деталям и живой поверхности материала, чтобы украшение не выглядело безликим предметом.</p><p>Визуальные материалы показывают мир мастерской и её объектов. Конкретные сроки, способы изготовления и доступность отдельных изделий уточняются отдельно.</p>${link("catalog", "Посмотреть украшения ↗", "class=text-link")}</div></section><section class="workshop-image">${image(photos.portrait, "Атмосферный образ из визуального архива ALTAR’")}</section><section class="custom section-wrap"><p class="eyebrow">Замысел, который ваш</p><h2>Создать свою<br><em>форму.</em></h2>${link("custom", "Об индивидуальном заказе ↗", "class=button-link")}</section></main>`,
  care: () => `<main id="main"><section class="care-hero"><div class="care-copy"><p class="eyebrow">Внимание к вещи</p><h1>Уход за<br><em>украшением.</em></h1><p>Несколько бережных привычек помогут сохранить любимую вещь в хорошем состоянии.</p></div><div class="care-image">${image(photos.blueRing, "Украшение ALTAR’ на спокойном фоне")}</div></section><section class="care-list section-wrap"><article><span>01</span><div><h2>Храните отдельно</h2><p>Отдельное мягкое место помогает избежать царапин и контакта с другими предметами.</p></div></article><article><span>02</span><div><h2>Снимайте перед делами</h2><p>Снимайте украшения перед спортом, уборкой, купанием и использованием бытовой химии.</p></div></article><article><span>03</span><div><h2>Очищайте мягко</h2><p>Используйте мягкую сухую ткань. Если нужна более глубокая чистка, сначала уточните безопасный способ у мастерской.</p></div></article></section><section class="care-note section-wrap"><p class="eyebrow">Нужна помощь?</p><h2>Состояние украшения<br>лучше оценить <em>индивидуально.</em></h2>${link("contacts", "Задать вопрос мастерской ↗", "class=text-link")}</section></main>`,
  contacts: () => `<main id="main"><section class="contact-page"><div class="contact-heading"><p class="eyebrow">На связи</p><h1>Поговорим<br><em>о вашей идее.</em></h1><p>Вопрос об украшении, заказе или уходе? Напишите мастерской — разберёмся вместе.</p></div><div class="contact-card"><span class="contact-mark">ALTAR’</span><p>Выберите тему, чтобы перейти к нужной странице сайта.</p><div>${link("catalog", "Украшения <span>↗</span>")}${link("custom", "Индивидуальный заказ <span>↗</span>")}${link("care", "Уход за украшениями <span>↗</span>")}</div><small>Контактные данные и каналы связи добавим после подтверждения официальных реквизитов.</small></div></section></main>`,
  cart: () => `<main id="main"><section class="page-intro cart-intro"><p class="eyebrow">Ваш выбор</p><h1>Корзина.</h1><p>Соберите подборку украшений, к которым хочется вернуться.</p></section><section class="cart-section section-wrap"><div id="cart-items"></div><div id="cart-summary" class="cart-summary"></div><p class="demo-note">Предпросмотр: оформление заказа и оплата пока не подключены.</p></section></main>`,
  checkout: () => `<main id="main"><section class="checkout-card"><p class="eyebrow">Предпросмотр сайта</p><h1>Заказ ещё<br><em>не оформлен.</em></h1><p>В этой версии сайта корзина работает локально в браузере. Перед запуском нужно подключить подтверждённую систему оформления и оплаты.</p>${link("cart", "Вернуться в корзину ↗", "class=button-link")}</section></main>`
};

document.getElementById("app").innerHTML = header + (pages[page] || pages.home)() + footer;

function getCart() { try { return JSON.parse(localStorage.getItem("altar-cart") || "{}"); } catch { return {}; } }
function setCart(cart) { localStorage.setItem("altar-cart", JSON.stringify(cart)); updateCartCount(); }
function updateCartCount() { const count = Object.values(getCart()).reduce((total, qty) => total + qty, 0); document.querySelectorAll("#cart-count").forEach((node) => node.textContent = String(count)); }
function renderCart() {
  const root = document.getElementById("cart-items");
  if (!root) return;
  const cart = getCart();
  const items = Object.entries(cart).map(([id, quantity]) => ({ item: products.find((product) => product.id === id), quantity })).filter(({ item }) => item);
  if (!items.length) { root.innerHTML = `<div class="empty-cart"><span>Пока здесь ничего нет</span><p>Посмотрите коллекцию и сохраните понравившиеся формы.</p>${link("catalog", "К украшениям ↗", "class=text-link")}</div>`; return; }
  root.innerHTML = items.map(({ item, quantity }) => `<article class="cart-item"><a class="cart-thumb" href="?page=product&id=${item.id}">${image(item.image, item.name)}</a><div class="cart-item-info"><a href="?page=product&id=${item.id}">${item.name}</a><span>${rubles(item.price)}</span><div class="quantity"><button data-qty="-1" data-id="${item.id}" aria-label="Уменьшить количество">−</button><span>${quantity}</span><button data-qty="1" data-id="${item.id}" aria-label="Увеличить количество">＋</button></div></div><button class="remove-item" data-remove="${item.id}">Убрать</button></article>`).join("");
  const total = items.reduce((sum, { item, quantity }) => sum + item.price * quantity, 0);
  document.getElementById("cart-summary").innerHTML = `<span>Предварительная сумма</span><strong>${rubles(total)}</strong><a class="button-link" href="?page=checkout">Продолжить <span aria-hidden=true>↗</span></a>`;
}
updateCartCount();
renderCart();

document.addEventListener("click", (event) => {
  const add = event.target.closest(".add-to-cart");
  if (add) { const cart = getCart(); cart[add.dataset.id] = (cart[add.dataset.id] || 0) + 1; setCart(cart); add.innerHTML = "Добавлено в корзину <span aria-hidden=true>✓</span>"; return; }
  const filter = event.target.closest(".filter-chip");
  if (filter) { document.querySelectorAll(".filter-chip").forEach((chip) => chip.classList.toggle("is-active", chip === filter)); const selected = filter.dataset.filter; document.getElementById("catalog-grid").innerHTML = productGrid(selected === "Все" ? products : products.filter((item) => item.type === selected)); return; }
  const quantity = event.target.closest("[data-qty]");
  const remove = event.target.closest("[data-remove]");
  if (quantity || remove) { const cart = getCart(); const id = quantity?.dataset.id || remove.dataset.remove; if (remove) delete cart[id]; else cart[id] = Math.max(0, (cart[id] || 0) + Number(quantity.dataset.qty)); if (!cart[id]) delete cart[id]; setCart(cart); renderCart(); }
  const menu = event.target.closest(".menu-button");
  if (menu) { const nav = document.querySelector(".main-nav"); const open = menu.getAttribute("aria-expanded") !== "true"; menu.setAttribute("aria-expanded", String(open)); nav.classList.toggle("is-open", open); }
});
