const products = [
  { id: "vesna-pendant", name: "ПОДВЕСКА [VESNA]", price: 14000, type: "Подвески", image: "https://static.tildacdn.com/stor6264-3536-4462-b733-303535363134/042a4087961a0bac1de4177bd278c4b4.jpg", story: "Про соединение четырёх сторон: тела, разума, чувств и души. Это не религиозный символ, это личная точка равновесия и баланса." },
  { id: "hidden-glow", name: "КОЛЬЦО {СКРЫТОЕ СИЯНИЕ}", price: 10000, type: "Кольца", image: "https://static.tildacdn.com/stor6637-6662-4836-a631-386332393965/25190ba15e94197b60a6881bc4f1f25a.jpg" },
  { id: "crimson-faith", name: "ПОДВЕСКА {БАГРОВАЯ ВЕРА}", price: 13500, type: "Подвески", image: "https://static.tildacdn.com/stor6239-3636-4834-a263-616563323833/35496349.jpg" },
  { id: "metamorphoses", name: "КОЛЬЦО {МЕТАМОРФОЗЫ}", price: 9500, type: "Кольца", image: "https://static.tildacdn.com/stor6632-6266-4633-a463-363634663165/c86714afa3a729593b300c2acecf7152.jpg" },
  { id: "yeah", name: "КОЛЬЦО-ПЕЧАТКА {YEAH}", price: 12000, type: "Кольца", image: "https://static.tildacdn.com/stor6663-6362-4337-b261-326533336433/2c7904d72db655348ffee874e863de81.jpg" },
  { id: "dangerous-beauty", name: "КОЛЬЦО-КАСТЕТ {ОПАСНАЯ КРАСОТА}", price: 10500, type: "Кольца", image: "https://static.tildacdn.com/stor6532-6266-4164-b464-346135626234/6582ae386a6147fb90a271d5243348a7.jpg" },
  { id: "vesna-ring", name: "КОЛЬЦО [VESNA]", price: 11000, type: "Кольца", image: "https://static.tildacdn.com/stor3834-3864-4862-b933-363034313936/1639a055955f726cfd462b61a2e7e40e.jpg" },
  { id: "sorry-cool", name: "ПОДВЕСКА {SORRY I’AM SO COOL}", price: 13000, type: "Подвески", image: "https://static.tildacdn.com/stor3437-3130-4465-a262-353863323532/999816ca63d2355ed08156725ba173aa.jpg" },
  { id: "not-like-others", name: "КОЛЬЦО {NOT LIKE OTHERS}", price: 10500, type: "Кольца", image: "https://static.tildacdn.com/stor3331-6639-4366-b632-343934363839/35466054.jpg" },
  { id: "wear-here", name: "КАФФ {ПОКА ЗДЕСЬ ПОНОШУ}", price: 7000, type: "Серьги", image: "https://static.tildacdn.com/stor6632-3761-4637-b037-666361643764/262a771c88bf31b3fa4060ef8160381f.jpg" },
  { id: "duality", name: "КОЛЬЦО {DUALITY}", price: 9500, type: "Кольца", image: "https://static.tildacdn.com/stor3633-3436-4932-a564-343636303662/b8fcfd799574de5ce5685a9b8740694d.jpg" },
  { id: "branches", name: "КОЛЬЦО {ВЕТВИ}", price: 10000, type: "Кольца", image: "https://static.tildacdn.com/stor6532-3132-4139-b232-613462313232/6755efaeb35a317919b46555989d48a1.jpg" }
];

const page = new URLSearchParams(location.search).get("page") || "home";
const activeProduct = products.find((item) => item.id === new URLSearchParams(location.search).get("id")) || products[0];
const rubles = (amount) => new Intl.NumberFormat("ru-RU").format(amount) + " ₽";
const link = (to, label, extra = "") => `<a ${extra} href="?page=${to}">${label}</a>`;
const image = (src, alt, cls = "") => `<img class="${cls}" src="${src}" alt="${alt}" loading="lazy">`;
const navItems = [["catalog", "Украшения"], ["workshop", "Мастерская"], ["custom", "Индивидуальный заказ"], ["care", "Уход"]];
const header = `<div class="announcement">Украшения, в которых есть место вашему смыслу</div><header class="site-header"><a class="wordmark" href="?page=home" aria-label="ALTAR’, главная">ALTAR<span>’</span></a><nav class="main-nav" aria-label="Основная навигация">${navItems.map(([to, title]) => link(to, title)).join("")}</nav><div class="header-actions">${link("contacts", "Контакты", "class=header-contact")}<a class="cart-link" href="?page=cart" aria-label="Корзина">Корзина <span id="cart-count">0</span></a></div><button class="menu-button" aria-label="Открыть меню" aria-expanded="false">Меню</button></header>`;
const footer = `<footer class="site-footer"><a class="wordmark" href="?page=home">ALTAR<span>’</span></a><p>Сделано с вниманием<br>в Москве</p><nav aria-label="Навигация в подвале">${navItems.map(([to, title]) => link(to, title)).join("")}${link("contacts", "Контакты")}</nav><span class="copyright">© ALTAR’</span></footer>`;
const productCard = (item) => `<article class="catalog-card"><a class="card-photo" href="?page=product&id=${item.id}">${image(item.image, `Украшение ALTAR’ — ${item.name}`)}<span class="card-arrow" aria-hidden="true">↗</span></a><div class="card-info"><a href="?page=product&id=${item.id}" class="card-name">${item.name}</a><span>${rubles(item.price)}</span></div><p class="card-kind">${item.type}</p></article>`;
const productGrid = (items) => `<div class="catalog-grid">${items.map(productCard).join("")}</div>`;

const pages = {
  home: () => `<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">Авторские украшения · Москва</p><h1>Украшения<br><em>со своим смыслом.</em></h1><p class="hero-intro">Украшения ALTAR’ — личные символы. Форма встречается с вашим собственным смыслом.</p>${link("catalog", 'Выбрать украшение <span aria-hidden="true">↗</span>', "class=text-link")}<div class="hero-index"><span>01</span><span class="index-rule"></span><span>Коллекция ALTAR’</span></div></div><figure class="hero-image">${image(products[8].image, "Кольцо ALTAR’ {Not Like Others}")}<figcaption>Кольцо {Not Like Others} <span>ALTAR’ · Москва</span></figcaption></figure></section><section class="intro section-wrap"><p class="eyebrow">Не украшение ради украшения</p><h2>Красота, в которой<br>можно <em>узнать себя.</em></h2><p class="intro-note">У вещи может быть своё значение. Вы решаете, каким оно станет.</p></section><section class="selection section-wrap"><div class="section-heading"><div><p class="eyebrow">01 / Выбранное</p><h2>Форма, созданная касанием руки</h2></div>${link("catalog", "Вся коллекция <span aria-hidden=true>↗</span>", "class=text-link")}</div>${productGrid(products.slice(0, 3))}</section><section class="craft"><div class="craft-image">${image(products[10].image, "Кольцо ALTAR’ {Duality}")}</div><div class="craft-copy"><p class="eyebrow">Создано вручную</p><h2>Материал.<br>Форма.<br><em>Прикосновение.</em></h2><p>У каждой вещи свой характер. Здесь фактура и форма говорят сами за себя.</p>${link("workshop", "О мастерской <span aria-hidden=true>↗</span>", "class=text-link")}</div></section><section class="custom section-wrap"><p class="eyebrow">Индивидуальный заказ</p><h2>Образ, который<br><em>пока существует только у вас.</em></h2>${link("custom", "Рассказать идею <span aria-hidden=true>↗</span>", "class=button-link")}</section></main>`,
  catalog: () => `<main id="main"><section class="page-intro"><p class="eyebrow">Объекты ALTAR’</p><h1>Украшения<br><em>своего смысла.</em></h1><p>Выберите форму, которая отзывается именно вам.</p></section><section class="catalog-section section-wrap"><div class="filter-row" role="group" aria-label="Фильтр по типу украшения"><button class="filter-chip is-active" data-filter="Все">Все украшения</button>${["Кольца", "Подвески", "Серьги"].map((name) => `<button class="filter-chip" data-filter="${name}">${name}</button>`).join("")}</div><div id="catalog-grid">${productGrid(products)}</div></section></main>`,
  product: () => `<main id="main"><div class="breadcrumbs">${link("home", "Главная")}<span>/</span>${link("catalog", "Украшения")}<span>/</span><span>${activeProduct.name}</span></div><section class="product-detail"><div class="detail-photo">${image(activeProduct.image, `Украшение ALTAR’ — ${activeProduct.name}`)}</div><div class="detail-copy"><p class="eyebrow">${activeProduct.type} · ALTAR’</p><h1>${activeProduct.name}</h1><p class="detail-price">${rubles(activeProduct.price)}</p><p class="detail-story">${activeProduct.story || "У вещи есть собственный характер. Пусть её значение сложится из вашей истории и того, как вы её носите."}</p><div class="fact-note">Подробности об изделии и доступности можно уточнить у мастерской.</div><button class="button-link add-to-cart" data-id="${activeProduct.id}">Добавить в корзину <span aria-hidden="true">＋</span></button><p class="detail-caption">Изображение из материалов ALTAR’</p></div></section><section class="related section-wrap"><div class="section-heading"><div><p class="eyebrow">Продолжить знакомство</p><h2>Другие формы</h2></div>${link("catalog", "Вся коллекция ↗", "class=text-link")}</div>${productGrid(products.filter((item) => item.id !== activeProduct.id).slice(0, 3))}</section></main>`,
  custom: () => `<main id="main"><section class="split-page"><div class="split-image">${image(products[5].image, "Кольцо-кастет ALTAR’ {Опасная красота}")}</div><div class="split-copy"><p class="eyebrow">Индивидуальный заказ</p><h1>Ваша идея.<br><em>Наша мастерская.</em></h1><p>Если нужная форма пока существует только в воображении, расскажите о ней. Можно обсудить украшение или другой объект из серебра.</p><div class="steps"><div><span>01</span><p>Опишите замысел и приложите референсы.</p></div><div><span>02</span><p>Мастерская обсудит форму и возможность работы.</p></div><div><span>03</span><p>Детали, сроки и стоимость согласуются отдельно.</p></div></div>${link("contacts", "Связаться с мастерской <span aria-hidden=true>↗</span>", "class=button-link")}</div></section></main>`,
  workshop: () => `<main id="main"><section class="workshop-hero"><div><p class="eyebrow">За каждым объектом — руки</p><h1>Мастерская<br><em>ALTAR’.</em></h1><p>Место, где материалу дают обрести собственную форму.</p></div><figure>${image(products[3].image, "Кольцо ALTAR’ {Метаморфозы}")}<figcaption>Форма в деталях</figcaption></figure></section><section class="workshop-story section-wrap"><div class="workshop-aside"><p class="eyebrow">Подход</p><span>01 — 03</span></div><div><h2>Не тираж.<br><em>Характер.</em></h2><p>ALTAR’ соединяет выразительную форму и личный смысл. Мы сохраняем внимание к деталям и живой поверхности материала, чтобы украшение не выглядело безликим предметом.</p><p>Визуальные материалы показывают мир мастерской и её объектов. Конкретные сроки, способы изготовления и доступность отдельных изделий уточняются отдельно.</p>${link("catalog", "Посмотреть украшения ↗", "class=text-link")}</div></section><section class="workshop-image">${image(products[7].image, "Подвеска ALTAR’ {SORRY I’AM SO COOL}")}</section><section class="custom section-wrap"><p class="eyebrow">Замысел, который ваш</p><h2>Создать свою<br><em>форму.</em></h2>${link("custom", "Об индивидуальном заказе ↗", "class=button-link")}</section></main>`,
  care: () => `<main id="main"><section class="care-hero"><div class="care-copy"><p class="eyebrow">Внимание к вещи</p><h1>Уход за<br><em>украшением.</em></h1><p>Несколько бережных привычек помогут сохранить любимую вещь в хорошем состоянии.</p></div><div class="care-image">${image(products[11].image, "Кольцо ALTAR’ {Ветви}")}</div></section><section class="care-list section-wrap"><article><span>01</span><div><h2>Храните отдельно</h2><p>Отдельное мягкое место помогает избежать царапин и контакта с другими предметами.</p></div></article><article><span>02</span><div><h2>Снимайте перед делами</h2><p>Снимайте украшения перед спортом, уборкой, купанием и использованием бытовой химии.</p></div></article><article><span>03</span><div><h2>Очищайте мягко</h2><p>Используйте мягкую сухую ткань. Если нужна более глубокая чистка, сначала уточните безопасный способ у мастерской.</p></div></article></section><section class="care-note section-wrap"><p class="eyebrow">Нужна помощь?</p><h2>Состояние украшения<br>лучше оценить <em>индивидуально.</em></h2>${link("contacts", "Задать вопрос мастерской ↗", "class=text-link")}</section></main>`,
  contacts: () => `<main id="main"><section class="contact-page"><div class="contact-heading"><p class="eyebrow">На связи</p><h1>Поговорим<br><em>о вашей идее.</em></h1><p>Вопрос об украшении, заказе или уходе? Напишите мастерской — разберёмся вместе.</p></div><div class="contact-card"><span class="contact-mark">ALTAR’</span><p>Выберите тему, чтобы перейти к нужной странице сайта.</p><div>${link("catalog", "Украшения <span>↗</span>")}${link("custom", "Индивидуальный заказ <span>↗</span>")}${link("care", "Уход за украшениями <span>↗</span>")}</div><small>Контактные данные и каналы связи добавим после подтверждения официальных реквизитов.</small></div></section></main>`,
  cart: () => `<main id="main"><section class="page-intro cart-intro"><p class="eyebrow">Ваш выбор</p><h1>Корзина.</h1><p>Соберите подборку украшений, к которым хочется вернуться.</p></section><section class="cart-section section-wrap"><div id="cart-items"></div><div id="cart-summary" class="cart-summary"></div><p class="demo-note">Предпросмотр: оформление заказа и оплата пока не подключены.</p></section></main>`,
  checkout: () => `<main id="main"><section class="checkout-card"><p class="eyebrow">Предпросмотр сайта</p><h1>Заказ ещё<br><em>не оформлен.</em></h1><p>В этой версии сайта корзина работает локально в браузере. Перед запуском нужно подключить подтверждённую систему оформления и оплаты.</p>${link("cart", "Вернуться в корзину ↗", "class=button-link")}</section></main>`
};

document.getElementById("app").innerHTML = header + (pages[page] || pages.home)() + footer;

function getCart() { try { return JSON.parse(localStorage.getItem("altar-cart") || "{}"); } catch { return {}; } }
function setCart(cart) { localStorage.setItem("altar-cart", JSON.stringify(cart)); updateCartCount(); }
function updateCartCount() { const count = Object.values(getCart()).reduce((total, qty) => total + qty, 0); document.querySelectorAll("#cart-count").forEach((node) => node.textContent = String(count)); }
function renderCart() {
  const root = document.getElementById("cart-items");
  if (!root) return;
  const cart = getCart();
  const items = Object.entries(cart).map(([id, quantity]) => ({ item: products.find((product) => product.id === id), quantity })).filter(({ item }) => item);
  if (!items.length) { root.innerHTML = `<div class="empty-cart"><span>Пока здесь ничего нет</span><p>Посмотрите коллекцию и сохраните понравившиеся формы.</p>${link("catalog", "К украшениям ↗", "class=text-link")}</div>`; return; }
  root.innerHTML = items.map(({ item, quantity }) => `<article class="cart-item"><a class="cart-thumb" href="?page=product&id=${item.id}">${image(item.image, item.name)}</a><div class="cart-item-info"><a href="?page=product&id=${item.id}">${item.name}</a><span>${rubles(item.price)}</span><div class="quantity"><button data-qty="-1" data-id="${item.id}" aria-label="Уменьшить количество">−</button><span>${quantity}</span><button data-qty="1" data-id="${item.id}" aria-label="Увеличить количество">＋</button></div></div><button class="remove-item" data-remove="${item.id}">Убрать</button></article>`).join("");
  const total = items.reduce((sum, { item, quantity }) => sum + item.price * quantity, 0);
  document.getElementById("cart-summary").innerHTML = `<span>Предварительная сумма</span><strong>${rubles(total)}</strong><a class="button-link" href="?page=checkout">Продолжить <span aria-hidden=true>↗</span></a>`;
}
updateCartCount();
renderCart();

document.addEventListener("click", (event) => {
  const add = event.target.closest(".add-to-cart");
  if (add) { const cart = getCart(); cart[add.dataset.id] = (cart[add.dataset.id] || 0) + 1; setCart(cart); add.innerHTML = "Добавлено в корзину <span aria-hidden=true>✓</span>"; return; }
  const filter = event.target.closest(".filter-chip");
  if (filter) { document.querySelectorAll(".filter-chip").forEach((chip) => chip.classList.toggle("is-active", chip === filter)); const selected = filter.dataset.filter; document.getElementById("catalog-grid").innerHTML = productGrid(selected === "Все" ? products : products.filter((item) => item.type === selected)); return; }
  const quantity = event.target.closest("[data-qty]");
  const remove = event.target.closest("[data-remove]");
  if (quantity || remove) { const cart = getCart(); const id = quantity?.dataset.id || remove.dataset.remove; if (remove) delete cart[id]; else cart[id] = Math.max(0, (cart[id] || 0) + Number(quantity.dataset.qty)); if (!cart[id]) delete cart[id]; setCart(cart); renderCart(); }
  const menu = event.target.closest(".menu-button");
  if (menu) { const nav = document.querySelector(".main-nav"); const open = menu.getAttribute("aria-expanded") !== "true"; menu.setAttribute("aria-expanded", String(open)); nav.classList.toggle("is-open", open); }
});
